### ISSUE TITLE
Public beta anytime soon?

### ISSUE THREAD

**Issue by sardaukar** [fluentdesk/fluentcv-issues#1]
Hey!

It's December 27th, one day after the public beta date on the website ;)

**Comment by aydjay** [comment]
Bumping for a beta release :)

**Comment by hacksalot** [comment]
Sorry for the delay -- FluentCV Desktop will be released when we have a solid v1.3 of HackMyResume, hopefully today, but if not, tomorrow. Release notices should change shortly to reflect that, and I'll follow up here too. Thanks!

**Comment by FrancoisBlavoet** [comment]
> hopefully today, but if not, tomorrow  

Am I missing something or has the beta been delayed ?

**Comment by sardaukar** [comment]
Is this ever going to happen now? :|
